### ISSUE TITLE
Cheaper checksum

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#446] opened 2023-04-27 06:42 UTC
The current checksum algorithm is a little expensive.  It would be easier to just concatenate all of the report IDs and hash the resulting stream.  SHA-256 implementations usually have an IUF interface.

**Comment by divergentdave** [comment] 2023-04-27 14:44
We need this checksum to not depend on the order of reports. The checksum gets updated with other accumulators as aggregation jobs finish (for the aggregate share, which is a field element vector, the number of reports included, and the time interval spanning all included report timestamps), and we need to tolerate the leader and helper adding contributions from different aggregation jobs in different orders. We could swap out SHA-256 for a cheaper function, and keep the same XOR accumulator structure.

**Comment by martinthomson** [comment] 2023-04-27 23:16
Ah, that's right.  I wonder if XOR without SHA-256 is enough, given the construction requirements on report IDs.

**Comment by cjpatton** [comment] 2023-04-28 21:16
I'm not sure, given that clients may choose the report IDs maliciously (i.e., not randomly generated). If a batch mismatch occurs, the clients may be able to pick report IDs such that the Aggregators compute the same checksum. For example, imagine the Leader computes `checkusm = ID1 ^ ID2` and the Helper computes `chuksum = ID3 ^ ID4`, where `ID1 ^ ID2 = ID3 ^ ID4`.

Hashing each ID is meant to make this harder, [but even this may be insufficient](https://twitter.com/David3141593/status/1649415552463503360). It would be sufficient to ensure the clients couldn't predict the value of the checksum.

**Comment by tgeoghegan** [comment] 2023-05-01 16:37
Let's keep in mind that when we introduced this hash, it wasn't designed as a security mechanism but rather a means of flushing out bugs in either implementations or the early drafts of the protocol itself. Point being: rather than reconsider which algorithms we use here, we might instead reconsider whether DAP needs this checksum at all. What we've said so far is that we need more operational experience with DAP to see how often the aggregators disagree on what reports belong to a given collection and I'm not sure we're there yet.

**Comment by cjpatton** [comment] 2023-05-01 16:43
Fair enough. So far this has not been an issue, but the highest load we've (Daphne) tried so far is only around 500 reports/s.

**Comment by branlwyd** [comment] 2023-05-01 21:01
The checksum/report-count functionality was useful in catching some implementation bugs during Janus load-testing. In these tests we could also have determined the error by looking to the aggregate output, since the inputs were known; but in a real deployment, this would not be possible. (only the Collector is exposed to the final aggregate, and it can only check correctness insofar as it can estimate plausibility of the aggregate value it receives.)

Given that in most real deployments, the Aggregators will be run by different organizations than the Collector, it would be very nice if the Aggregators could determine if there was a report mismatch somehow before they sent bad data to the Collector, whose organization they may view as a client/subscriber to their service.

**Comment by simon-friedberger** [comment] 2023-06-19 11:15
I think we're all on the same page so just to be explicit: I see no need for this checksum from a privacy or robustness point of view.

**Comment by chris-wood** [comment] 2023-10-19 21:33
@simon-friedberger I'm not sure we are on the same page here. @branlwyd suggests that keeping this checksum around to help catch failures in production is a useful tool. I can imagine some deployments wanting to keep this around indefinitely, whereas other deployments removing after they reach a certain level of confidence in their batch agreement logic. Perhaps we can split the difference by making checksum an optional value for aggregators?

**Comment by cjpatton** [comment] 2023-10-19 23:19
In our (Cloudflare) own internal experiments, we have triggered the condition that the checksum mechanism was designed to detect. Speaking as an operator, I want to make sure we keep this signal in the protocol.

I'd be open to simplifying it, or making it optional as @chris-wood's PR proposes. However, we should also recognize that the cost of the checksum is quite low when we compare it to the heavier weight crypto that surrounds it (HPKE decryption, VDAF preparation).

**Comment by tgeoghegan** [comment] 2023-10-23 17:32
I'm wary of adding optional or conditional behavior to the protocol. I think a per-task option for the checksum is the most we should ever do about this -- I definitely don't want any more complex in-band signaling to govern whether aggregators will include a checksum for a particular aggregate share.

**Comment by simon-friedberger** [comment] 2023-10-25 07:53
@chris-wood To clarify: This may catch errors and be useful, but it is not necessary for the privacy guarantees nor for the robustness guarantees.

**Comment by cjpatton** [comment] 2023-11-07 13:46
At IETF 118, we decided to close this issue without action. Folks were leaning towards making it optional, but since it's relatively cheap we decided optimization here is mostly a bike shed.

**Closed by cjpatton** 2023-11-07 13:46 UTC
Labels: ietf118
