### ISSUE TITLE
Separate report shares from aggregation parameters

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-ppm/draft-ietf-ppm-dap#230] opened 2022-04-28 16:41 UTC
Currently, the aggregation process begins by the leader sending report shares and aggregation parameters _together_ to each helper. @ekr observes that this is not strictly necessary, as the verification process should discard any reports that are invalid in the end, and the leader can cause each helper to store bogus report shares indefinitely anyway. Splitting up sharing report shares and aggregation parameters might help some implementations, e.g., by allowing the leader to stream report shares to each aggregator before initiating aggregation. For Prio3, this isn't much helpful since aggregation can begin without the collector's input. For Poplar, this might be very useful.

**Comment by ekr** [comment] 2022-04-28 16:58
Maybe I'm confused. How is `agg_param` computed? I had thought it was constant for a given instance, because this document does not seem to define it as an output.

**Comment by divergentdave** [comment] 2022-04-28 17:05
`agg_param` is chosen by the collector, and sent to the leader in a `CollectReq`. For the case of Prio3, this parameter is the unit type, but for Poplar1, it will be a candidate prefix.

Splitting up how report shares and aggregation parameters are sent will have an additional benefit for the Poplar1 case, in that it would allow the leader to send report shares to the helper only once, for reuse in multiple different aggregations with different candidate prefixes. This would be a significant bandwidth win.

**Comment by ekr** [comment] 2022-04-28 17:14
I'm not against splitting them up, but I was just making a much more trivial point, which was that the leader can send the shares to the helper prior to locally initializing. I thought there was some text here that said that, but now I can't find it so maybe I misread or maybe it changed.

**Comment by cjpatton** [comment] 2022-05-04 18:23
> I'm not against splitting them up, but I was just making a much more trivial point, which was that the leader can send the shares to the helper prior to locally initializing. I thought there was some text here that said that, but now I can't find it so maybe I misread or maybe it changed.

Sure, but the helper will only be able to decrypt them. It won't be able to begin processing them until it knows `agg_param` (at least in general). I suppose it might be useful to permit the helper to decrypt immediately to reduce the chance of the HPKE config getting rotated before it has a chance to decrypt.

In any case, I think this change is a good idea for the reason mentioned by @divergentdave.

**Comment by tgeoghegan** [comment] 2023-05-26 21:25
Technically #405 is a dupe of this issue, but since #405 has more concrete design proposals in it, I'm going to reverse-dupe and close this one.

**Closed by tgeoghegan** 2023-05-26 21:25 UTC
